version: '3'
services:
  mariadb:
    image: mariadb:10.4
    volumes:
      - ${PWD}/volumes/mariadb:/var/lib/mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:6
    volumes:
      - ${PWD}/volumes/redis:/data
    ports: 
      - 6379:6379